spring.application.name=DockerDataBase
server.port=8081

# Database connection
spring.datasource.url=jdbc:mysql://mysql:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true